### PR TITLE
Add search bar

### PR DESCRIPTION
**Pull request by kpolnitz**
Adds a search bar to the IDE. When entering characters into the search bar, it will display the lines that contain the characters. Basic functionality right now, with plans to add more features in the future.

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
What happens after you find the line you are looking for? Is there a way to show all the lines again but still highlight the found line?

**Comment by kpolnitz** [comment]
> What happens after you find the line you are looking for? Is there a way to show all the lines again but still highlight the found line?

It will basically only display lines that match the query. There is a quick clear button that allows you to view the normal code. I think the way I have it configured that should be a pretty easy add!

**Comment by tannewt** [comment]
Neat! Is this ready for another review?

**Comment by kpolnitz** [comment]
Sure! When keywords are entered now, it should highlight the line in a yellow-orange color instead of deleting the other lines.

**Review by tannewt — APPROVED** [review]
Thank you! This sounds great!

**Pull request merged**
